/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "quiz.h"
#include<string.h>

void
quiz_prog_1(char *host,char *user_id)
{
	
	CLIENT *clnt;
	quiz_sr_home  *result_1;
	quiz_cl_home  quizproc_1_arg;
	quiz_sr_que  *result_2;
	quiz_cl_req  quizquestionproc_1_arg;
	quiz_sr_reply  *result_3;
	quiz_cl_ans  replyproc_1_arg;
	quiz_sr_pos  *result_4;
	quiz_cl_pos  getpos_1_arg;
	quiz_sr_lboard  *result_5;
	quiz_cl_lboard  getleaderboard_1_arg;
	quiz_sr_end  *result_6;
	quiz_cl_end  quizend_1_arg;


#ifndef	DEBUG
	clnt = clnt_create (host, QUIZ_PROG, QUIZ_VERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	//set user_id for every procedure call.......................
	strcpy(quizproc_1_arg.id,user_id);
	strcpy(replyproc_1_arg.id,user_id);
	strcpy(quizend_1_arg.id,user_id);
	strcpy(quizquestionproc_1_arg.id,user_id);
	strcpy(getpos_1_arg.id,user_id);
	strcpy(getleaderboard_1_arg.id,user_id);


	//send connection  request with user_id.....................
	result_1 = quizproc_1(&quizproc_1_arg, clnt);
	if (result_1 == (quiz_sr_home *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	char wish,leader;
	char answer[512];
	int question=0;
	printf("\n\t\t*******************welcome %s !*************** \n\t\t Do you want to play a quiz? Press Y to play : ",result_1->id);
	scanf(" %c",&wish);
	
	printf("\n\t\tcurrent score : %d position : %d\n",result_1->score,result_1->pos);

	while(wish=='Y'||wish=='y')
	{
		
		question++;	
		//request for a question.............................
	
		result_2 = quizquestionproc_1(&quizquestionproc_1_arg, clnt);
		if (result_2 == (quiz_sr_que *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		fflush(stdout);

		//show question......................................
		printf("\n\t\tquestion(%d) : %s\n",question,result_2->question);
		fflush(stdout);
		printf("\t\tyour answer: ");
		fflush(stdout);

		scanf(" %[^\n]%*c", answer);

		strcpy(replyproc_1_arg.answer,answer);		
		replyproc_1_arg.que_no=result_2->que_no;

		//Display result...........................................
		result_3 = replyproc_1(&replyproc_1_arg, clnt);
		if (result_3 == (quiz_sr_reply *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		result_4 = getpos_1(&getpos_1_arg, clnt);
		if (result_4 == (quiz_sr_pos *) NULL) {
		clnt_perror (clnt, "call failed");
		}
		printf("\n\t\tyour answer is  %s\n\t\tscore : %d position : %d\n",result_3->reply,result_3->score,result_4->pos);
		printf("\n\t\tDo you want to see the leaderboard?\n\t\tPress Y to view : ");
		scanf(" %c",&leader);
		if(leader=='Y'||leader=='y')
		{
			printf("\n\t\t*******************LEADER BOARD***************\n");
			printf("\n\t\t----------------------------------------------");


		printf("\n\t\t\tUSER ID             |\tSCORE\n");
		printf("\t\t----------------------------------------------\n");


		for(int i=0;i<3;i++)
		{
			getleaderboard_1_arg.index=i;
			 result_5 = getleaderboard_1(&getleaderboard_1_arg, clnt);
                if (result_5 == (quiz_sr_lboard *) NULL) {
                        clnt_perror (clnt, "call failed");
                }


printf("\t\t\t%-20s|\t%-5d\n",result_5->leader_id,result_5->leader_score);
printf("\t\t----------------------------------------------\n");



}

		}
		
		printf("\n\t\tPress Y to continue or other character to quit : ");
		fflush(stdout);
		scanf(" %c",&wish);
		
	}

	//ending quiz...........................................
		
	result_6 = quizend_1(&quizend_1_arg, clnt);
	if (result_6 == (quiz_sr_end *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("\t\tDear, %s your final score was %d and position was %d\n",result_6->id,result_6->score,result_6->pos);
	printf("\t\tSee you again!!\n");
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char user_id[20];

	if (argc != 2) {
		printf ("\t\tusage: %s server_address\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("\n\t\tEnter your username: ");
	 scanf(" %[^\n]%*c", user_id);
	

	quiz_prog_1 (host,user_id);
	exit (0);
}
