/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "quiz.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

quiz_sr_home *
quizproc_1(quiz_cl_home *argp, CLIENT *clnt)
{
	static quiz_sr_home clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, QUIZPROC,
		(xdrproc_t) xdr_quiz_cl_home, (caddr_t) argp,
		(xdrproc_t) xdr_quiz_sr_home, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

quiz_sr_que *
quizquestionproc_1(quiz_cl_req *argp, CLIENT *clnt)
{
	static quiz_sr_que clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, QUIZQUESTIONPROC,
		(xdrproc_t) xdr_quiz_cl_req, (caddr_t) argp,
		(xdrproc_t) xdr_quiz_sr_que, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

quiz_sr_reply *
replyproc_1(quiz_cl_ans *argp, CLIENT *clnt)
{
	static quiz_sr_reply clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REPLYPROC,
		(xdrproc_t) xdr_quiz_cl_ans, (caddr_t) argp,
		(xdrproc_t) xdr_quiz_sr_reply, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

quiz_sr_pos *
getpos_1(quiz_cl_pos *argp, CLIENT *clnt)
{
	static quiz_sr_pos clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETPOS,
		(xdrproc_t) xdr_quiz_cl_pos, (caddr_t) argp,
		(xdrproc_t) xdr_quiz_sr_pos, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

quiz_sr_lboard *
getleaderboard_1(quiz_cl_lboard *argp, CLIENT *clnt)
{
	static quiz_sr_lboard clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GETLEADERBOARD,
		(xdrproc_t) xdr_quiz_cl_lboard, (caddr_t) argp,
		(xdrproc_t) xdr_quiz_sr_lboard, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

quiz_sr_end *
quizend_1(quiz_cl_end *argp, CLIENT *clnt)
{
	static quiz_sr_end clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, QUIZEND,
		(xdrproc_t) xdr_quiz_cl_end, (caddr_t) argp,
		(xdrproc_t) xdr_quiz_sr_end, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
